version: "3.9"

networks:
  destacame:

services:
  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
            POSTGRES_DB: destacame
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - destacame
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: frontend
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - destacame
    ports:
      - 8080:8080
    expose:
      - 8080
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: backend
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - destacame
volumes:
  database:

